#!/bin/bash

sed -i 's/127.0.0.1/8.8.8.8/' /etc/resolv.conf

apt update -y

apt upgrade -y

apt-get install acl attr samba winbind libpam-winbind samba-client libnss-winbind dnsutils python3-setproctitle -y

for VARIABLE in $(smbd -b | egrep "LOCKDIR|STATEDIR|CACHEDIR|PRIVATE_DIR" | cut -d ":" -f2)
do
  echo "Borrando *.tdb y *.ldb en $VARIABLE"
  rm -Rf $VARIABLE/*.tdb
  rm -Rf $VARIABLE/*.ldb
done

rm -Rf $(smbd -b | grep "CONFIGFILE" | cut -d ":" -f2)

systemctl stop smbd nmbd winbind
systemctl disable smbd nmbd winbind

samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm=RPAI-TIPY-UY.DUCKDNS.ORG --domain=RPAI-TIPY-UY --adminpass=Passw0rd

sed -i 's/8.8.8.8/127.0.0.1/' /etc/resolv.conf

samba

host -t SRV _ldap._tcp.rpai-tipy-uy.duckdns.org

host -t SRV _kerberos._udp.rpai-tipy-uy.duckdns.org

host -t A 4-RP-addc01.rpai-tipy-uy.duckdns.org






apt-get update
apt-get upgrade -y 


apt-get install acl attr autoconf bind9utils bison build-essential \
  debhelper dnsutils docbook-xml docbook-xsl flex gdb libjansson-dev krb5-user \
  libacl1-dev libaio-dev libarchive-dev libattr1-dev libblkid-dev libbsd-dev \
  libcap-dev libcups2-dev libgnutls28-dev libgpgme-dev libjson-perl \
  libldap2-dev libncurses5-dev libpam0g-dev libparse-yapp-perl \
  libpopt-dev libreadline-dev nettle-dev perl pkg-config \
  python3-dev python3-dbg python3-crypto python3-dnspython python3-gpg python3-markdown \
  xsltproc zlib1g-dev liblmdb-dev lmdb-utils





samba-tool ou create "OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=ServiceAccounts,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Equipos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Proveedores,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Ex-Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Desktops,OU=Equipos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Servers,OU=Equipos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Grupos_de_Seguridad,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Grupos_Distribuidos,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool ou create "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool group add devs
samba-tool group move "devs" "OU=Grupos_de_Seguridad,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool group add rrhh
samba-tool group move "rrhh" "OU=Grupos_de_Seguridad,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool group add proxmox-admins
samba-tool group move "proxmox-admins" "OU=Grupos_de_Seguridad,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool group add sysadmins
samba-tool group move "sysadmins" "OU=Grupos_de_Seguridad,OU=Grupos,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"


samba-tool user create 'Carlos Martínez' 'Passw0rd'
samba-tool user create 'Laura López' 'Passw0rd'
samba-tool user create 'Juan Hernández' 'Passw0rd'
samba-tool user create 'Jesus Guibert' 'Passw0rd'
samba-tool user create 'Rodrigo Palivoda' 'Passw0rd'

samba-tool user create 'David Gómez' 'Passw0rd'
samba-tool user create 'Sandra Ramírez' 'Passw0rd'
samba-tool user create 'Alejandro Torres' 'Passw0rd'
samba-tool user create 'Patricia Morales' 'Passw0rd'
samba-tool user create 'Javier Ortiz' 'Passw0rd'


samba-tool user create 'Beatriz Navarro' 'Passw0rd'
samba-tool user create 'Raúl Gil' 'Passw0rd'
samba-tool user create 'María Soto' 'Passw0rd'
samba-tool user create 'Antonio Castro' 'Passw0rd'
samba-tool user create 'Isabel Ramos' 'Passw0rd'
samba-tool user create 'Jorge Vega' 'Passw0rd'


samba-tool user move "Carlos Martínez" "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Laura López" "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Juan Hernández" "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Jesus Guibert" "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Rodrigo Palivoda" "OU=Sysadmins,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool user move "David Gómez" "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Sandra Ramírez" "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Alejandro Torres" "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Patricia Morales" "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Javier Ortiz" "OU=Devs,OU=Sistemas,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"

samba-tool user move "Beatriz Navarro" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Raúl Gil" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "María Soto" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Antonio Castro" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Isabel Ramos" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"
samba-tool user move "Jorge Vega" "OU=RRHH,OU=Empleados,OU=Usuarios,OU=rpai-tipy-uy.duckdns.org,DC=rpai-tipy-uy,DC=duckdns,DC=org"


samba-tool group addmembers 'proxmox-admins' 'Jesus Guibert'
samba-tool group addmembers 'proxmox-admins' 'Rodrigo Palivoda'

samba-tool group addmembers 'rrhh' 'Beatriz Navarro'
samba-tool group addmembers 'rrhh' 'Raúl Gil'
samba-tool group addmembers 'rrhh' 'María Soto'
samba-tool group addmembers 'rrhh' 'Antonio Castro'
samba-tool group addmembers 'rrhh' 'Isabel Ramos'
samba-tool group addmembers 'rrhh' 'Jorge Vega'

samba-tool group addmembers 'devs' 'David Gómez'
samba-tool group addmembers 'devs' 'Sandra Ramírez'
samba-tool group addmembers 'devs' 'Alejandro Torres'
samba-tool group addmembers 'devs' 'Patricia Morales'
samba-tool group addmembers 'devs' 'Javier Ortiz'

samba-tool group addmembers 'sysadmins' 'Carlos Martínez'
samba-tool group addmembers 'sysadmins' 'Laura López'
samba-tool group addmembers 'sysadmins' 'Juan Hernández'
samba-tool group addmembers 'sysadmins' 'Jesus Guibert'
samba-tool group addmembers 'sysadmins' 'Rodrigo Palivoda'
